### ISSUE TITLE
Missing docker image for 1.10.0 release

### ISSUE THREAD

**Issue by dnskr** [apache/kyuubi-docker#15]
The workflow `Publish Docker image` was not triggered on release PR https://github.com/apache/kyuubi-docker/pull/14 merge, so the image was not built and published to Docker Hub:
```shell
docker pull apache/kyuubi:1.10.0

Error response from daemon: manifest for apache/kyuubi:1.10.0 not found: manifest unknown: manifest unknown
```

**Comment by dnskr** [comment]
@bowenliang123 Could you please have a look at it?

**Comment by bowenliang123** [comment]
Thank you for the reminder. It seems that the v1.10.0 tag was missed in the push. Let me retrigger it. (https://github.com/apache/kyuubi-docker/actions/runs/11788579533/job/32835920032)

**Comment by bowenliang123** [comment]
It's now ready on Dockerhub with v1.10.0 tags.
https://hub.docker.com/layers/apache/kyuubi/1.10.0/images/sha256-c1e2a7631013edd7fcf64e7435b0afde3d79e75ece0577a3fc3aea1626427425?context=explore
