### ISSUE TITLE
Is there a public Dockerfile to build out the image with Kyuubi v1.6.1?

### ISSUE THREAD

**Issue by GaryShen2008** [apache/kyuubi-docker#5]
I ran "docker build" with the https://github.com/apache/kyuubi-docker/blob/master/1.6.1-incubating/scala2.12-java8-ubuntu/Dockerfile. But it seems it couldn't build out a valid image.
And I couldn't find a v1.6.1 tag in https://hub.docker.com/r/apache/kyuubi.

Is there any plan to publish a usable Dockerfile or docker image for v1.6.1?

**Comment by ulysses-you** [comment]
@GaryShen2008 if you want to build a custom image, you can follow https://github.com/apache/kyuubi/blob/master/docker/Dockerfile

The Dockerfile in thie repo is used for github CI which can not be used by end user

BTW, we are planning to release 1.7.0 tag

**Comment by ulysses-you** [comment]
v1.7.0 is ready now

**Comment by GaryShen2008** [comment]
Great. Thanks for the information. I'd like to try 1.7.0.
